### ISSUE TITLE
Licensing Considerations

### ISSUE THREAD

**Issue by zauberparacelsus** [jonsneyers/FLIF#27]
I'd like to ask that the use of GPL licensing be reconsidered.  The GPL is primarily intended for applications, IE software that gets into the hands of end users (who may or may not wish to tinker with it).    In doing so, however, it sacrifices some of the freedoms of application developers.

Developers who wish to use FLIF in their project would be forced to license it as GPL, and doing so would mean (A) sacrificing their freedom to license their project according to their needs and/or personal wishes, and (B) it would mean that other libraries they may wish to use would automatically not be an option because they are not under GPL-compatible licenses.

Because of those, it can mean that FLIF cannot be used in some projects.  And I will note that none of the major browsers in use are GPL-licensed: they are either proprietary or licensed under permissive open source licenses.  (The exception to this is firefox, which allows developers to choose between GPL, LGPL, and MPL according to their needs).  The libraries that browsers use to support established image standards, libpng, libjpeg, giflib, openJPEG, and Jasper, are all under permissive licenses.

FLIF is advertised as being royalty-free and unencumbered by software patents.  But the unfortunate reality is that the GPL is as much of a barrier to adoption as royalty fees and software patents, because just like those it places additional restrictions upon developers.  Sadly, the GPL is simply not flexible enough to accommodate the needs of larger open source projects.  And although you may not like proprietary software much, their support is needed as well in order for FLIF to become an established standard, and they won't support it if it is GPL.

So, I would like to propose that the following alternatives be considered:
A) Allowing exemptions to some of the non-permissive terms of the GPL, or allow developers to request an alternative license that better suits their needs.  Some open source projects make money with paid exemptions, which can be used to finance further development on the project by paying for developer time.
B) Adopt a permissive license.  No major developer freedoms are sacrificed with this route.  However, you lose one advantage of the GPL, which is the requirement that fixes and improvements to the library itself be contributed back if publicly distributed.
C) Adopt the LGPL.  It is a much better fit for libraries than the GPL.  It preserves the GPL's requirement for improvements/fixes to be contributed back, but without forcing developers to change their licensing, and it doesn't produce a licensing conflict that prevents the usage of other libraries.

**Comment by jimtarber** [comment]
This is indeed a problem for many developers, and I fully support this suggestion. I'd love to (eventually) replace use our heavy use of JPEG2000 with FLIF, or at least add it as an option, but the GPL license actually encumbers FLIF and may actually be the sole reason for lack of adoption.  

I suspect that this was not the intention when GPL was chosen; it seems the intention was to provide something unencumbered, so a less restrictive alternative such LGPL.

Another alternative is something as simple as the one we use [here](https://github.com/InWorldz/halcyon/blob/master/LICENSE) for our Halcyon license.

**Comment by jonsneyers** [comment]
I am aware of how the GPL works. See also https://github.com/jonsneyers/FLIF/issues/3 for more license discussion.
For now, when the format is not yet finalized, the GPL is just fine and will help to avoid premature adoption. When the format is finalized, we'll probably release the reference implementation under the LGPL and/or Apache2 license. The spec itself will be public, maybe an RFC or something, at some point.

**Comment by lehitoskin** [comment]
[This article](https://gnu.org/licenses/why-not-lgpl.html) comes to mind. The big question we should be asking is whether or not this project should pander to proprietary companies who may or may not use FLIF in the first place. One of the biggest reasons for using strong copyleft licenses like the GPL is to give free software projects an edge over proprietary companies who may have many, many times the budget of a typical free software project.

@zauberparacelsus 
>Developers who wish to use FLIF in their project would be forced to license it as GPL

Technically, only if they distribute binaries of the program.

>And I will note that none of the major browsers in use are GPL-licensed

I assume you mean to say the three biggest browsers being Internet Explorer/Edge, Firefox, and Google Chrome. Firefox is under the tri-license, Internet Explorer/Edge is proprietary, and Google Chrome is freeware; however, Chrome is built on top of Chromium, which is actually under the tri-license LGPL/GPL/MPL. I would argue this is slightly more than "none".

>And although you may not like proprietary software much, their support is needed as well in order for FLIF to become an established standard, and they won't support it if it is GPL.

You want to know what the most popular free software project in the world is? The Linux kernel. It has support from every major software company you can think of. Hell, even Microsoft sends patches to the kernel.  I will grant that it would be an uphill battle getting FLIF to be a widely-used standard, but saying it's impossible because it uses a copyleft license is silly, because it's almost impossible to get a new standard to be The Next Big Thing™, not matter the license. Even PNG took a very long time before it saw any kind of wide usage and Jpeg 2000 never saw that kind of popularity.

>A) Allowing exemptions to some of the non-permissive terms of the GPL, or allow developers to request an alternative license that better suits their needs. Some open source projects make money with paid exemptions, which can be used to finance further development on the project by paying for developer time.

Like Qt. They allow proprietary developers to pay a licensing fee to use it in their projects outside the GPL. I don't particularly think anything would come from this unless it was already popular. Who would want to pay any amount of money for a format nobody supports (yet)?

>B) Adopt a permissive license. No major developer freedoms are sacrificed with this route. However, you lose one advantage of the GPL, which is the requirement that fixes and improvements to the library itself be contributed back if publicly distributed.

There's a reason Sony chose FreeBSD as the base for their PS4 operating system: it was free for them to take the hard work of the developers and then make a proprietary fork with zero obligation to give back to the community. This is the worst aspect of non-copyleft licenses and I very much recommend against this.

>C) Adopt the LGPL. It is a much better fit for libraries than the GPL. It preserves the GPL's requirement for improvements/fixes to be contributed back, but without forcing developers to change their licensing, and it doesn't produce a licensing conflict that prevents the usage of other libraries.

This is the most reasonable change that could be done to the license.  While using the GPL for this reference library would be perfect if it was an open standard (which would allow someone else to create an implementation under MIT or a proprietary license), there is no such thing since it's still in its infancy stage. While I ranted and raved about the GPL, there is a high possibility that if FLIF is under the GPL, companies might just keep using PNG or JPEG and never think twice about it. Again, as I said earlier in the post, it is very difficult to get any new format to be accepted or widely used, so this whole thing might be moot.

One possible avenue of approach to getting FLIF adopted is to get it implemented in browsers, but that's a different topic.

**Comment by PallHaraldsson** [comment]
"The exception to this is firefox, which allows developers to choose between GPL, LGPL, and MPL according to their needs" or put another way: "Firefox is under the tri-license" is actually not strictly true, or hasn't been for a long time now. It's under MPL 2.0 (which is GPL-compatible, by default).

LGPL has been proposed, a weaker copyleft, MPL 2.0 is similar, but as I understand even weaker, that is "file-based". Otherwise more or less the same (e.g. for patents (and trademarks?). I am not a lawyer..

I new (OSI-approved) license I just discovered could also be an option (that seems very understandable/short):

The Universal Permissive License (UPL), Version 1.0
https://opensource.org/licenses/UPL

If you really like copyleft, MPL 2.0 seems the best compromize (Apache 2.0 not (as GPL-compatible), otherwise UPL..

GPL (any version) doesn't strictly rule out proprietary software, you could use FLIF in a separate process with a clear interface that gave you decompressed BMP or whatever.. (I guess not as good for Windows where processes are expensive vs. threads..).
